#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinTest.Resource", IsApplication=true)]

namespace XamarinTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int star_accent = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int star_disabled = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int timetable_accept_button_free = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int timetable_accept_button_occupied = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int timetable_list_item_available = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int timetable_list_item_unavailable = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int view_pager_item_accent = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int view_pager_item_color = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int view_pager_item_dayoff = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int view_pager_item_disabled = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_half_important = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_important = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_next_item = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_not_important = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_previous_item = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int photo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int view_pager_border = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int button_book = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int date_name_text = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int date_value_text = 2131230738;
			
			// aapt resource value: 0x7f080006
			public const int header_description_text = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int header_price_info_text = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int header_price_text = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int header_title_text = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int list_view_timetable = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int rating_star1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int rating_star2 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int rating_star3 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int rating_star4 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int rating_star5 = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int root = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int timetable_accept = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int timetable_description_text = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int timetable_time_text = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int view_pager = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int viewpager_button_next = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int viewpager_button_previous = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int timetable_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int view_pager_item_fragment = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int timetable_descr1 = 2131099660;
			
			// aapt resource value: 0x7f060015
			public const int timetable_descr10 = 2131099669;
			
			// aapt resource value: 0x7f06000d
			public const int timetable_descr2 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int timetable_descr3 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int timetable_descr4 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int timetable_descr5 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int timetable_descr6 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int timetable_descr7 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int timetable_descr8 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int timetable_descr9 = 2131099668;
			
			// aapt resource value: 0x7f060002
			public const int timetable_time1 = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int timetable_time10 = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int timetable_time2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int timetable_time3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int timetable_time4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int timetable_time5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int timetable_time6 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int timetable_time7 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int timetable_time8 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int timetable_time9 = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
